openapi: 3.0.0
info:
  title: musical-bingo
  description: ''
  version: "v1"
paths:
  /user:
    get:
      summary: 5ed7b3202e305a694fbc22d4
      description: return the information about the user
      operationId: 5ed7b3202e305a694fbc22d4
      security:
        - bearerAuth: []
      responses:
        '200':
          description: details of the current user
          content:
            application/json:
              schema:
                $ref: '#/components/responses/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      summary: 5ed7b320b43d718ef98ebbb8
      description: "Attempt to log in.\n"
      operationId: 5ed7b320b43d718ef98ebbb8
      requestBody:
        description: Username and password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: details of the user that is now logged in
          content:
            application/json:
              schema:
                $ref: '#/components/responses/User'
    put:
      description: Register a new user
      requestBody:
        description: Username and password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: details of the user that has been created
          content:
            application/json:
              schema:
                $ref: '#/components/responses/NewUser'
    delete:
      description: Log out current user
      responses:
        '200':
          description: log out confirmation
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        rememberme:
          type: boolean
    DecoratedUserObject:
      description: Description of a user
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        last_login:
          type: string
          format: date-time
        groups:
          type: array
          items:
            type: string
        options:
          $ref: '#/components/schemas/OptionsObject'
        accessToken:
          type: string
        refreshToken:
          type: string
    OptionsObject:
      description: Game options
      type: object
      properties:
        colourScheme:
          type: string
        colourSchemes:
          type: array
          items:
            type: string
        maxTickets:
          type: integer
        rows:
          type: integer
        columns:
          type: integer
    RegisterRequest:
      description: Request payload for registering a user
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    RegisterResponse:
      description: Response to registering a new user
      type: object
      properties:
        message:
          type: string
        success:
          type: boolean
        user:
          $ref: '#/components/schemas/DecoratedUserObject'
        accessToken:
          type: string
        refreshToken:
          type: string

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    User:
      $ref: '#/components/schemas/DecoratedUserObject'
    NewUser:
      $ref: '#/components/schemas/RegisterResponse'
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/garibaldi-redhill/musical-bingo/v1
  - description: Azure API gateway
    url: https://musical-bingo-api-v1.azure-api.net/api
