# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'client'
    env:
       TZ: 'UTC'
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.11
        uses: actions/setup-node@v4
        with:
          node-version: 20.11
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Generate build
        run: npm run build
      - name: Unit tests
        run: npm run coverage
      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: client-coverage
          path: |
            client/coverage/index.html
            client/coverage/*.css
            client/coverage/*.js
          if-no-files-found: error
          retention-days: 30
