name: Python application

on: [push]

jobs:
  build310:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
  build311:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Static type check with mypy
      run: |
        pip install mypy==0.991
        mypy musicbingo
    - name: Lint with pylint
      run: |
        pip install pylint==2.17.4
        pylint --rcfile=.pylintrc musicbingo
