name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Static type check with mypy
      run: |
        pip install mypy
        mypy musicbingo
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --rcfile=.pylintrc musicbingo
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
