name: Python application

on: [push]

jobs:
  build36:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Static type check with mypy
      run: |
        pip install mypy
        mypy musicbingo
  build39:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Static type check with mypy
      run: |
        pip install mypy
        mypy musicbingo
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --rcfile=.pylintrc musicbingo
  build310:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Static type check with mypy
      run: |
        pip install mypy
        mypy musicbingo
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --rcfile=.pylintrc musicbingo
